/**
 * Storage layer, built on Node's own SQLite so there is no dependency, no
 * server and nothing to run. Fine for synthetic testing. When real client
 * answers arrive this moves to managed Postgres, and the schema is written so
 * that move is a port rather than a redesign.
 */

import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Household, PlanEvaluation } from "../types.ts";
import type { ShortlistEntry } from "../rank.ts";
import type { SubsidyResult } from "../subsidy.ts";
import type { Versions } from "./versions.ts";

export interface StoreOptions {
  /** Path to the SQLite file. Use ":memory:" for throwaway runs. */
  file: string;
  schemaPath?: string;
}

export class Store {
  private db: DatabaseSync;

  constructor(opts: StoreOptions) {
    this.db = new DatabaseSync(opts.file);
    const schema = readFileSync(
      opts.schemaPath ?? join(import.meta.dirname, "schema.sql"),
      "utf8",
    );
    this.db.exec(schema);
    this.migrate();
  }

  /**
   * Adds columns that arrived after a database was first created.
   *
   * CREATE TABLE IF NOT EXISTS does nothing to a table that already exists, so
   * a column added to schema.sql never reaches an older file. SQLite has no
   * ADD COLUMN IF NOT EXISTS, hence the read of the existing shape first.
   *
   * Only additive, nullable or defaulted columns belong here. Anything that
   * needs data moved wants a real migration with a version table, and if that
   * day comes before the move to Postgres this should be replaced rather than
   * extended.
   */
  private migrate(): void {
    const added: Array<[string, string, string]> = [
      ["recommendation_run", "state", "TEXT NOT NULL DEFAULT 'NJ'"],
      ["recommendation_run", "rating_area", "TEXT"],
      ["recommendation_run", "state_rules_version", "TEXT"],
    ];
    for (const [table, column, definition] of added) {
      const existing = this.db.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>;
      if (existing.some((c) => c.name === column)) continue;
      this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
  }

  close(): void {
    this.db.close();
  }

  private now(): string {
    return new Date().toISOString();
  }

  ensureAgency(id: string, name: string, state = "NJ"): string {
    this.db
      .prepare(
        `INSERT INTO agency (id, name, state, created_at) VALUES (?, ?, ?, ?)
         ON CONFLICT(id) DO NOTHING`,
      )
      .run(id, name, state, this.now());
    return id;
  }

  /**
   * Issues a client code. Generated by the system rather than by a person, so
   * uniqueness is guaranteed, and drawn from an alphabet with no characters
   * that can be confused when read down a phone: no O against 0, no I or L
   * against 1.
   */
  issueClientCode(agencyId: string, label?: string): string {
    const ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
    for (let attempt = 0; attempt < 50; attempt += 1) {
      let code = "";
      for (let i = 0; i < 6; i += 1) {
        code += ALPHABET[Math.floor(Math.random() * ALPHABET.length)];
      }
      const clash = this.db
        .prepare(`SELECT 1 FROM client_code WHERE code = ? AND agency_id = ?`)
        .get(code, agencyId);
      if (clash) continue;
      this.db
        .prepare(
          `INSERT INTO client_code (code, agency_id, label, created_at) VALUES (?, ?, ?, ?)`,
        )
        .run(code, agencyId, label ?? null, this.now());
      return code;
    }
    throw new Error("Could not generate an unused client code after 50 attempts");
  }

  /**
   * Records what the client entered. Immutable: a correction is a new
   * submission, never an update, so the original answers survive.
   */
  recordSubmission(input: {
    agencyId: string;
    clientCode: string;
    answers: unknown;
    questionnaireVersion: string;
    isSynthetic?: boolean;
    notes?: string;
  }): string {
    const id = randomUUID();
    const at = this.now();
    this.db
      .prepare(
        `INSERT INTO submission
           (id, agency_id, client_code, submitted_at, questionnaire_version, answers, is_synthetic, notes)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.agencyId,
        input.clientCode,
        at,
        input.questionnaireVersion,
        JSON.stringify(input.answers),
        input.isSynthetic ? 1 : 0,
        input.notes ?? null,
      );
    this.db
      .prepare(
        `UPDATE client_code SET consumed_at = ? WHERE code = ? AND agency_id = ? AND consumed_at IS NULL`,
      )
      .run(at, input.clientCode, input.agencyId);
    return id;
  }

  /**
   * Records one execution of the engine, with enough version detail to
   * reproduce or diagnose it later, plus every plan it priced rather than
   * only the shortlist.
   */
  recordRun(input: {
    submissionId: string;
    agencyId: string;
    planYear: number;
    versions: Versions;
    household: Household;
    subsidy: SubsidyResult;
    evaluations: PlanEvaluation[];
    shortlist: ShortlistEntry[];
    silverVariant: string;
    flags: string[];
    /** Defaults to New Jersey, the only state whose rules exist. */
    state?: string;
    ratingArea?: string;
  }): string {
    const runId = randomUUID();
    const eligible = input.evaluations.filter((e) => e.disqualifiers.length === 0);

    this.db
      .prepare(
        `INSERT INTO recommendation_run
           (id, submission_id, agency_id, created_at, plan_year, state, rating_area,
            engine_version, state_rules_version,
            plan_data_version, assumptions_version, fpl_percentage, silver_variant,
            federal_subsidy, plans_evaluated, plans_eligible, flags, full_result)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        runId,
        input.submissionId,
        input.agencyId,
        this.now(),
        input.planYear,
        input.state ?? "NJ",
        input.ratingArea ?? null,
        input.versions.engine,
        input.versions.stateRules ?? null,
        input.versions.planData,
        input.versions.assumptions,
        input.subsidy.fplPercentage,
        input.silverVariant,
        input.subsidy.federalAnnualSubsidy,
        input.evaluations.length,
        eligible.length,
        JSON.stringify(input.flags),
        JSON.stringify(
          input.evaluations.map((e) => ({
            planId: e.plan.planId,
            issuer: e.plan.issuerName,
            name: e.plan.marketingName,
            metal: e.plan.metalLevel,
            premium: e.cost.annualPremiumNet,
            oop: e.cost.estimatedOutOfPocket,
            total: e.cost.estimatedAnnualTotal,
            worst: e.cost.worstCaseAnnualTotal,
            disqualifiers: e.disqualifiers,
          })),
        ),
      );

    const insert = this.db.prepare(
      `INSERT INTO shortlist_entry
         (id, run_id, rank, tier, plan_id, issuer_name, marketing_name, metal_level,
          annual_premium, expected_oop, expected_total, worst_case_total, rationale)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    );
    input.shortlist.forEach((pick, i) => {
      const { plan, cost } = pick.evaluation;
      insert.run(
        randomUUID(),
        runId,
        i + 1,
        pick.tier,
        plan.planId,
        plan.issuerName,
        plan.marketingName,
        plan.metalLevel,
        cost.annualPremiumNet,
        cost.estimatedOutOfPocket,
        cost.estimatedAnnualTotal,
        cost.worstCaseAnnualTotal,
        pick.rationale,
      );
    });

    return runId;
  }

  /**
   * Records what the agent did with the shortlist. This is the row that makes
   * the whole database worth having.
   */
  recordAgentReview(input: {
    runId: string;
    agencyId: string;
    agentName: string;
    presentedPlanIds: string[];
    recommendedPlanId?: string;
    overrideReason?: string;
    timeSpentMinutes?: number;
  }): string {
    const id = randomUUID();
    const top = this.db
      .prepare(`SELECT plan_id FROM shortlist_entry WHERE run_id = ? ORDER BY rank LIMIT 1`)
      .get(input.runId) as { plan_id?: string } | undefined;
    const followed =
      input.recommendedPlanId && top?.plan_id
        ? input.recommendedPlanId === top.plan_id
          ? 1
          : 0
        : null;

    this.db
      .prepare(
        `INSERT INTO agent_review
           (id, run_id, agency_id, agent_name, reviewed_at, presented_plan_ids,
            recommended_plan_id, followed_engine, override_reason, time_spent_minutes)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.runId,
        input.agencyId,
        input.agentName,
        this.now(),
        JSON.stringify(input.presentedPlanIds),
        input.recommendedPlanId ?? null,
        followed,
        input.overrideReason ?? null,
        input.timeSpentMinutes ?? null,
      );
    return id;
  }

  recordOutcome(input: {
    runId: string;
    agencyId: string;
    enrolled: boolean;
    enrolledPlanId?: string;
    notes?: string;
  }): string {
    const id = randomUUID();
    this.db
      .prepare(
        `INSERT INTO outcome (id, run_id, agency_id, recorded_at, enrolled_plan_id, enrolled, notes)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.runId,
        input.agencyId,
        this.now(),
        input.enrolledPlanId ?? null,
        input.enrolled ? 1 : 0,
        input.notes ?? null,
      );
    return id;
  }

  /**
   * Records what the agent did to one plan, and what they said about it.
   *
   * raw_note goes in exactly as spoken or typed. Nothing here interprets it:
   * the classifier runs later and writes to plan_action_label, so a note is
   * never overwritten by our reading of it.
   */
  recordPlanAction(input: {
    runId: string;
    agencyId: string;
    agentName: string;
    planId: string;
    action: "led_with" | "ruled_out";
    rank?: number | null;
    rawNote?: string;
    noteSource?: "voice" | "typed";
    noteMs?: number;
    piiSuspected?: boolean;
    actedAt?: string;
  }): string {
    const id = randomUUID();
    this.db
      .prepare(
        `INSERT INTO plan_action
           (id, run_id, agency_id, agent_name, acted_at, plan_id, rank, action,
            raw_note, note_source, note_ms, pii_suspected)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.runId,
        input.agencyId,
        input.agentName,
        input.actedAt ?? this.now(),
        input.planId,
        input.rank ?? null,
        input.action,
        input.rawNote ?? null,
        input.noteSource ?? null,
        input.noteMs ?? null,
        input.piiSuspected ? 1 : 0,
      );
    return id;
  }

  /**
   * Records one reading of one note. Re-running the classifier under a new
   * taxonomy adds rows rather than replacing them, so which codes were in
   * force when a note was labelled stays answerable.
   */
  recordActionLabel(input: {
    actionId: string;
    taxonomyVersion: string;
    labelledBy: string;
    kind?: string;
    topic?: string;
    detail?: string;
    subject?: string;
    confidence?: number;
  }): string {
    const id = randomUUID();
    this.db
      .prepare(
        `INSERT INTO plan_action_label
           (id, action_id, labelled_at, taxonomy_version, kind, topic, detail,
            subject, confidence, labelled_by)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.actionId,
        this.now(),
        input.taxonomyVersion,
        input.kind ?? null,
        input.topic ?? null,
        input.detail ?? null,
        input.subject ?? null,
        input.confidence ?? null,
        input.labelledBy,
      );
    return id;
  }

  /**
   * Notes with no label under the current taxonomy. Feeds the classifier, and
   * is the whole work queue after a taxonomy revision.
   */
  unlabelledActions(taxonomyVersion: string): Array<{
    id: string;
    plan_id: string;
    action: string;
    rank: number | null;
    raw_note: string;
  }> {
    return this.query(
      `SELECT a.id, a.plan_id, a.action, a.rank, a.raw_note
         FROM plan_action a
        WHERE a.raw_note IS NOT NULL AND TRIM(a.raw_note) <> ''
          AND NOT EXISTS (
            SELECT 1 FROM plan_action_label l
             WHERE l.action_id = a.id AND l.taxonomy_version = ?
          )
        ORDER BY a.acted_at`,
      taxonomyVersion,
    );
  }

  /**
   * Finds the run the browser was looking at, keyed on the submission's own
   * timestamp, which is the only handle a page with no server can hold.
   */
  findRunBySubmittedAt(submittedAt: string): string | null {
    const row = this.query<{ id: string }>(
      `SELECT r.id FROM recommendation_run r
         JOIN submission s ON s.id = r.submission_id
        WHERE s.submitted_at = ?
        ORDER BY r.created_at DESC LIMIT 1`,
      submittedAt,
    )[0];
    return row?.id ?? null;
  }

  /**
   * A run to hang notes off when the real one is not in this database.
   *
   * The browser and this file are not yet connected, so a note taken on the
   * hosted page has no run here to point at. Losing the note would be the
   * worse outcome, so it lands against a placeholder that is marked synthetic
   * and carries no figures, and the numbers stay honestly absent rather than
   * being invented.
   */
  placeholderRun(input: {
    agencyId: string;
    submittedAt: string;
    planYear: number;
    state?: string;
  }): string {
    const existing = this.findRunBySubmittedAt(input.submittedAt);
    if (existing) return existing;

    const submissionId = randomUUID();
    this.db
      .prepare(
        `INSERT INTO submission
           (id, agency_id, client_code, submitted_at, questionnaire_version, answers, is_synthetic, notes)
         VALUES (?, ?, ?, ?, ?, ?, 1, ?)`,
      )
      .run(
        submissionId,
        input.agencyId,
        "unlinked",
        input.submittedAt,
        "unknown",
        "{}",
        "Placeholder. Created on import so an agent note had somewhere to live; the engine run itself happened in a browser and was never recorded here.",
      );

    const runId = randomUUID();
    this.db
      .prepare(
        `INSERT INTO recommendation_run
           (id, submission_id, agency_id, created_at, plan_year, state, engine_version,
            plan_data_version, assumptions_version, fpl_percentage, silver_variant,
            federal_subsidy, plans_evaluated, plans_eligible, flags, full_result)
         VALUES (?, ?, ?, ?, ?, ?, 'unlinked', 'unlinked', 'unlinked', NULL, 'unknown', NULL, 0, 0, '[]', '{}')`,
      )
      .run(runId, submissionId, input.agencyId, this.now(), input.planYear, input.state ?? "NJ");

    return runId;
  }

  /** True when this action was already imported, keyed on the browser's own id. */
  hasPlanAction(id: string): boolean {
    return this.query(`SELECT 1 AS n FROM plan_action WHERE id = ?`, id).length > 0;
  }

  /** Inserts with a caller supplied id, so re-importing an export is a no op. */
  recordPlanActionWithId(id: string, input: Parameters<Store["recordPlanAction"]>[0]): boolean {
    if (this.hasPlanAction(id)) return false;
    this.db
      .prepare(
        `INSERT INTO plan_action
           (id, run_id, agency_id, agent_name, acted_at, plan_id, rank, action,
            raw_note, note_source, note_ms, pii_suspected)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.runId,
        input.agencyId,
        input.agentName,
        input.actedAt ?? this.now(),
        input.planId,
        input.rank ?? null,
        input.action,
        input.rawNote ?? null,
        input.noteSource ?? null,
        input.noteMs ?? null,
        input.piiSuspected ? 1 : 0,
      );
    return true;
  }

  query<T = Record<string, unknown>>(sql: string, ...params: unknown[]): T[] {
    return this.db.prepare(sql).all(...(params as never[])) as T[];
  }
}
